services:

  # nginx
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - internal

  # php
  php:
    container_name: php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./src/:/var/www/html/
    networks:
      - internal

networks:
  internal:
    driver: bridge
